name: Update blog posts
on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://pablocaro.es/feeds/all.atom.xml"
          max_post_count: 5
          commit_message: "📝 Update latest blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
